import { WeaponDTO } from "./weapon";

export const weapons : WeaponDTO[] = [
    new WeaponDTO(10.5, .68, 1, true, 'CBC', 'charred mallorn mace' ),
    new WeaponDTO(4.5, 1.5, .75, false, '1 orc steel ingot', 'angmar dagger'),
    new WeaponDTO(7.5, 1, 1, false, '2 orc steel ingots', 'angmar sword'),
    new WeaponDTO(9.5, 0.75, 1, false, '5 orc steel ingots', 'angmar  battleaxe'),
    new WeaponDTO(10.5, .65, 1, true, '4 orc  steel  ingots', 'angmar warhammer'),
    new WeaponDTO(6.5, .83, 1.5, false, '1 orc steel ingot', 'angmar spear'),
    new WeaponDTO(7.5, .68, 1.5, false, '3 orc steel ingot', 'angmar poleaxe'),
    new WeaponDTO(4.5, 1.5, .75, false, 'CBC', 'arnorian dagger'),
    new WeaponDTO(7.5, 1, 1, false, 'CBC', 'arnorian sword'),
    new WeaponDTO(6.5, .83, 1.5, false, 'CBC', 'arnorian spear'),
    new WeaponDTO(4.5, 1.5, 0.75, false, 'CBC', 'black númenórean dagger'),
    new WeaponDTO(7.5, 1, 1, false,  'CBC', 'black númenórean sword'),
    new WeaponDTO(6.5, .83, 1.5, false, 'CBC', 'black númenórean spear'),
    new WeaponDTO(10.5, .65, 1, true, 'CBC', 'black númenórean mace'),
    new WeaponDTO(5, 1.5, 0.75, false, '1 black uruk steel ingot', 'black uruk dagger'),
    new WeaponDTO(8, 1, 1, false, '2 black uruk steel ingots', 'black uruk cleaver'),
    new WeaponDTO(10, .75, 1, false, '5 black uruk steel ingots', 'black uruk battleaxe'),
    new WeaponDTO(7, .83, 1.5, false, '1 black uruk steel ingot', 'black uruk spear'),
    new WeaponDTO(11, .65, 1, true, '4 black uruk steel ingots', 'black uruk warhammer'),
    new WeaponDTO(5, 1.5, .75, false, '1 blue dwarven ingot', 'blue dwarven dagger'),
    new WeaponDTO(8, 1, 1, false, '2 blue dwarven ingots', 'blue dwarven sword'),
    new WeaponDTO(10, .75, 1, false, '5 blue dwarven ingots', 'blue dwarven battleaxe'),
    new WeaponDTO(11, .65, 1, true,  '4 blue dwarven ingots', 'blue dwarven warhammer'),
    new WeaponDTO(7, .83, 1.5, false, '1 blue dwarven ingot', 'blue dwarven spear'),
    new WeaponDTO(8, .5, 2, false, '2 blue dwarven ingot', 'blue dwarven pike'),
    new WeaponDTO(6.5, 1, 1, false, '2 bronze ingots', 'bronze sword'),
    new WeaponDTO(3.5, 1.5, .75, false, '1 bronze ingot', 'bronze dagger'),
    new WeaponDTO(5.5, .83, 1.5, false, '1 bronze ingot', 'bronze spear'),
    new WeaponDTO(8.5, .75, 1, false, '5 bronze ingots', 'bronze battleaxe'),
    new WeaponDTO(4.5, 1.5, .75, false, '1 iron ingot', 'corsair dagger'),
    new WeaponDTO(7.5, 1, 1, false, '2 iron ingots', 'corsair eket'),
    new WeaponDTO(6.5, .83, 1.5, false, '1 iron ingot', 'corsair harpoon'),
    new WeaponDTO(9.5, .75, 1, false, '5 iron ingots', 'corsair battleaxe'),
    new WeaponDTO(8, 1, 1, false, '2 iron ingots', 'dol amroth sword'),
    new WeaponDTO(5, 1.5, .75, false, '1 iron ingot', 'dol amroth dagger'),
    new WeaponDTO(8, .5, 2, true, '2 iron ingots', 'dol amroth lance'),
    new WeaponDTO(8, .5, 2, false, '2 iron ingots', 'dol amroth longspear'),
    new WeaponDTO(7.5, 1, 1, false, '2 orc steel ingots', 'dol guldur sword'),
    new WeaponDTO(4.5, 1.5, .75, false, '1 orc steel ingot', 'dol guldur dagger'),
    new WeaponDTO(9.5, .75, 1, false, '5 orc steel ingot', 'dol guldur battleaxe'),
    new WeaponDTO(10.5, .65, 1, true, '4 orc steel ingots', 'dol guldur warhammer'),
    new WeaponDTO(6.5, .83, 1.5, false, '1 orc steel ingot', 'dol guldur spear'),
    new WeaponDTO(7.5, .5, 2, false, '2 orc steel ingot', 'dol guldur spike'),
    new WeaponDTO(5, 1.5, .75, false, '1 elven steel ingot', 'dorwinion elven dagger'),
    new WeaponDTO(8, 1, 1, false, '2 elven steel ingot', 'dorwinion elven sword'),
    new WeaponDTO(6.5, .83, 1.5, false, '1 dwarven steel ingot', 'spear of bladorthin'),
    new WeaponDTO(5, .65, 1, true, '3 planks', 'dunlending club'),
    new WeaponDTO(7, .68, 1.5, false, '3 iron ingots', 'dunlending trident'),
    new WeaponDTO(5, 1.5, .75, false, '1 dwarven steel ingot', 'dwarven dagger'),
    new WeaponDTO(8, 1, 1, false, '2 dwarven steel ingots', 'dwarven sword'),
    new WeaponDTO(10, .75, 1, false, '5 dwarven steel ingots', 'dwarven battleaxe'),
    new WeaponDTO(11, .65, 1, true, '4 dwarven steel ingots', 'dwarven warhammer'),
    new WeaponDTO(7, .83, 1.5,false, '1 dwarven steel ingot', 'dwarven spear'),
    new WeaponDTO(8, .5, 2, false, '2 dwarven steel ingots', 'dwarven pike'),
    new WeaponDTO(5, 1.5, .75, false, '1 elven steel ingot', 'galadhrim dagger'),
    new WeaponDTO(8, 1.1, .75, false, '2 elven steel ingots', 'galadhrim sword'),
    new WeaponDTO(7, .83, 1.5, false, '1 elven steel ingot', 'galadhrim spear'),
    new WeaponDTO(8, .5, 2, false, '2 elven steel ingots', 'galadhrim longspear'),
    new WeaponDTO(8, .68, 1.5, false, '2 elven steel ingots', 'galadhrim battlestaff'),
    new WeaponDTO(10, 1, 1, false, 'CBC', 'gondolinian sword'),
    new WeaponDTO(7.5, 1, 1, false, '2 iron ingots', 'gondorian sword'),
    new WeaponDTO(4.5, 1.5, .75, false, '1 iron ingots', 'gondorian dagger'),
    new WeaponDTO(10.5, .65, 1, true, '4 iron ingots', 'gondorian warhammer'),
    new WeaponDTO(6.5, .83, 1.5, false, '1 iron ingot', 'gondorian spear'),
    new WeaponDTO(7.5, .5, 2, true, '2 iron ingot', 'gondorian lance'),
    new WeaponDTO(7.5, .5, 2, false, '2 iron ingot', 'gondorian pike'),
    new WeaponDTO(7.5, 1, 1, false, '2  bronze ingots', 'gulfen khopesh'),
    new WeaponDTO(4.5, 1.5, .75, false, '1 flint', 'half-troll dagger'),
    new WeaponDTO(7.5, 1, 1, false, '2 flint', 'half-troll dagger'),
    new WeaponDTO(7.5, .5, 2, false, '2 flint', 'half-troll pike'),
    new WeaponDTO(10.5, .65, 1, true, '4 flint', 'half-troll warhammer'),
    new WeaponDTO(10.5, .65, 1, true, '4 flint', 'half-troll mace'),
    new WeaponDTO(9.5, .75, 1, false, '5 flint', 'half-troll battleaxe'),
    new WeaponDTO(7.5, 1, 1, false, '2 bronze ingots', 'haradic sword'),
    new WeaponDTO(4.5, 1.5, .75, false, '1 bronze ingot', 'haradic dagger'),
    new WeaponDTO(6.5, .83, 1.5, false, '1 bronze ingot','haradic spear'),
    new WeaponDTO(7.5, .5, 2, false, '2 bronze ingots', 'haradic longspear'),
    new WeaponDTO(9.5, .68, 1, true, 'CBC', 'blacksmith hammer'),
    new WeaponDTO(5, 1.5, .75, false, '1 elven steel ingot', 'lindon dagger'),
    new WeaponDTO(8, 1, 1, false, '2 elven steel ingots', 'lindon sword'),
    new WeaponDTO(7, .83, 1.5,  false, '1 elven steel ingot', 'lindon spear'),
    new WeaponDTO(8, .65, 1.5, false, '2 elven steel ingots', 'lindon battlestaff'),
    new WeaponDTO(8, .5, 2, false, '2 elven steel ingots', 'lindon longspear'),
    new WeaponDTO(9, .75, 1, false, '5 iron ingots', 'lossarnach battleaxe'),
    new WeaponDTO(6.5, 1, 1, false, '2 mallorn planks', 'mallorn sword'),
    new WeaponDTO(7, 1.5, .75, false, '1 mithril ingot', 'mithril dagger'),
    new WeaponDTO(10, 1, 1, false,  '2 mithril ingots', 'mithril sword'),
    new WeaponDTO(12, .75, 1, false, '5 mithril ingots',  'mithril battleaxe'),
    new WeaponDTO(13, .65, 1, true, '4 mithril ingots', 'mithril warhammer'),
    new WeaponDTO(9, .83, 1.5, false, '1 mithril ingot', 'mithril spear'),
    new WeaponDTO(10, .5, 2, false, '3 mithril ingots','mithril halberd'),
    new WeaponDTO(4.5, 1.5, .75, false, '1 orc steel ingot', 'mordor dagger'),
    new WeaponDTO(7.5, 1, 1, false, '2 orc steel ingots', 'mordor scimitar'),
    new WeaponDTO(6.5, .83, 1.5, false, '1 orc steel ingot', 'mordor spear'),
    new WeaponDTO(8.5, .75, 1, false, '5 orc steel ingots', 'mordor battleaxe'),
    new WeaponDTO(9.5, .65, 1, true, '4 orc steel ingots', 'mordor warhammer'),
    new WeaponDTO(7.5, .68, 1.5, false, '3 orc steel ingots', 'mordor warscythe'),
    new WeaponDTO(4.5, 1.5, .75, false, 'CBC', 'old-haradic sacrificial dagger'),
    new WeaponDTO(6.5, 1, 1, true, '1 skeleton skull', 'orc skull staff'),
    new WeaponDTO(7.5, .68, 1.5, false, '3 iron ingots', 'pelargir trident'),
    new WeaponDTO(6.5, 1, 1, false, '2 iron ingots', 'pelargir eket'),
    new WeaponDTO(5.5, 1.5, .75, false, 'CBC', 'utumno dagger'),
    new WeaponDTO(8.5, 1, 1, false, 'CBC', 'utumno sword'),
    new WeaponDTO(7.5, .83, 1.5, false, 'CBC', 'utumno spear'),
    new WeaponDTO(10.5, .75, 1, false, 'CBC', 'utumno battleaxe'),
    new WeaponDTO(11.5, .68, 1, true, 'CBC', 'utumno warhammer'),
    new WeaponDTO(4.5, 1.5, .75, false, '1 iron ingot', 'rhûnic dagger'),
    new WeaponDTO(7.5, 1, 1, false, '2 iron ingot', 'rhûnic sword'),
    new WeaponDTO(6.5, .83, 1.5, false, '1 iron ingot', 'rhûnic spear'),
    new WeaponDTO(7.5, .83, 1.5, false, '3 iron ingots', 'rhûnic bardiche'),
    new WeaponDTO(7.5, .5, 2, false, '2 iron ingots', 'rhûnic pike'),
    new WeaponDTO(9.5, .75, 1, false, '5 iron ingots', 'rhûnic battleaxe'),
    new WeaponDTO(5, 1.5, .75, false, '1 elven steel ingot', 'rivendell dagger'),
    new WeaponDTO(8, 1, 1, false, '2 elven steel ingots', 'rivendell sword'),
    new WeaponDTO(7, .83, 1.5,  false, '1 elven steel ingot', 'rivendell spear'),
    new WeaponDTO(8, .65, 1.5, false, '2 elven steel ingots', 'rivendell battlestaff'),
    new WeaponDTO(8, .5, 2, false, '2 elven steel ingots', 'rivendell longspear'),
    new WeaponDTO(4.5, 1.5, .75, false, '1 iron ingot', 'rohirric dagger'),
    new WeaponDTO(7.5, 1, 1, false, '2 iron ingots', 'rohirric sword'),
    new WeaponDTO(6.5, .83, 1.5, false, '1 iron ingot', 'rohirric spear'),
    new WeaponDTO(9.5, .75, 1, false, '5 iron ingots', 'rohirric battleaxe'),
    new WeaponDTO(7.5, .5, 2, false, '2 iron  ingots', 'rohirric lance'),
    new WeaponDTO(5, 1, 1, false, '1 plank', 'rolling pin'),
    new WeaponDTO(4.5, 1.5, .75, false,'1 iron ingot', 'umbaric dagger'),
    new WeaponDTO(7.5,1,1, false, '2 iron ingots', 'umbaric scimitar'),
    new WeaponDTO(6.5, .83, 1.5, false, '1 iron ingot', 'umbaric spear'),
    new WeaponDTO(7.5, .68, 1.5, false, '3 iron ingots', 'umbaric poleaxe'),
    new WeaponDTO(10.5, .65, 1, true, '4 iron ingots', 'umbaric mace'),
    new WeaponDTO(7.5, .5, 2, false, '2 iron ingots', 'umbaric pike'),
    new WeaponDTO(5, 1.5, .75, false, '1 elven steel ingot', 'wood-elven dagger'),
    new WeaponDTO(8, 1, 1, false, '2 elven steel ingots', 'wood-elven sword'),
    new WeaponDTO(7, .83, 1.5, false, '1 elven steel ingot', 'wood-elven spear'),
    new WeaponDTO(8, .68, 1.5, false, '2 elven steel ingots', 'wood-elven battlestaff'),
    new WeaponDTO(8, .5, 2, false, '2 elven ingots', 'wood-elven longspear'),    
]
