import { Weapon } from "./weapon";

export const weapons : Record<string, Weapon>  = {};

const source : Weapon[] = [
    new Weapon(10.5, .68, 1, true, 'CBC', 'charred mallorn mace' ),
    new Weapon(4.5, 1.5, .75, false, '1 orc steel ingot', 'angmar dagger'),
    new Weapon(7.5, 1, 1, false, '2 orc steel ingots', 'angmar sword'),
    new Weapon(9.5, 0.75, 1, false, '5 orc steel ingots', 'angmar  battleaxe'),
    new Weapon(10.5, .65, 1, true, '4 orc  steel  ingots', 'angmar warhammer'),
    new Weapon(6.5, .83, 1.5, false, '1 orc steel ingot', 'angmar spear'),
    new Weapon(7.5, .68, 1.5, false, '3 orc steel ingot', 'angmar poleaxe'),
    new Weapon(4.5, 1.5, .75, false, 'CBC', 'arnorian dagger'),
    new Weapon(7.5, 1, 1, false, 'CBC', 'arnorian sword'),
    new Weapon(6.5, .83, 1.5, false, 'CBC', 'arnorian spear'),
    new Weapon(4.5, 1.5, 0.75, false, 'CBC', 'black númenórean dagger'),
    new Weapon(7.5, 1, 1, false,  'CBC', 'black númenórean sword'),
    new Weapon(6.5, .83, 1.5, false, 'CBC', 'black númenórean spear'),
    new Weapon(10.5, .65, 1, true, 'CBC', 'black númenórean mace'),
    new Weapon(5, 1.5, 0.75, false, '1 black uruk steel ingot', 'black uruk dagger'),
    new Weapon(8, 1, 1, false, '2 black uruk steel ingots', 'black uruk cleaver'),
    new Weapon(10, .75, 1, false, '5 black uruk steel ingots', 'black uruk battleaxe'),
    new Weapon(7, .83, 1.5, false, '1 black uruk steel ingot', 'black uruk spear'),
    new Weapon(11, .65, 1, true, '4 black uruk steel ingots', 'black uruk warhammer'),
    new Weapon(5, 1.5, .75, false, '1 blue dwarven ingot', 'blue dwarven dagger'),
    new Weapon(8, 1, 1, false, '2 blue dwarven ingots', 'blue dwarven sword'),
    new Weapon(10, .75, 1, false, '5 blue dwarven ingots', 'blue dwarven battleaxe'),
    new Weapon(11, .65, 1, true,  '4 blue dwarven ingots', 'blue dwarven warhammer'),
    new Weapon(7, .83, 1.5, false, '1 blue dwarven ingot', 'blue dwarven spear'),
    new Weapon(8, .5, 2, false, '2 blue dwarven ingot', 'blue dwarven pike'),
    new Weapon(6.5, 1, 1, false, '2 bronze ingots', 'bronze sword'),
    new Weapon(3.5, 1.5, .75, false, '1 bronze ingot', 'bronze dagger'),
    new Weapon(5.5, .83, 1.5, false, '1 bronze ingot', 'bronze spear'),
    new Weapon(8.5, .75, 1, false, '5 bronze ingots', 'bronze battleaxe'),
    new Weapon(4.5, 1.5, .75, false, '1 iron ingot', 'corsair dagger'),
    new Weapon(7.5, 1, 1, false, '2 iron ingots', 'corsair eket'),
    new Weapon(6.5, .83, 1.5, false, '1 iron ingot', 'corsair harpoon'),
    new Weapon(9.5, .75, 1, false, '5 iron ingots', 'corsair battleaxe'),
    new Weapon(8, 1, 1, false, '2 iron ingots', 'dol amroth sword'),
    new Weapon(5, 1.5, .75, false, '1 iron ingot', 'dol amroth dagger'),
    new Weapon(8, .5, 2, true, '2 iron ingots', 'dol amroth lance'),
    new Weapon(8, .5, 2, false, '2 iron ingots', 'dol amroth longspear'),
    new Weapon(7.5, 1, 1, false, '2 orc steel ingots', 'dol guldur sword'),
    new Weapon(4.5, 1.5, .75, false, '1 orc steel ingot', 'dol guldur dagger'),
    new Weapon(9.5, .75, 1, false, '5 orc steel ingot', 'dol guldur battleaxe'),
    new Weapon(10.5, .65, 1, true, '4 orc steel ingots', 'dol guldur warhammer'),
    new Weapon(6.5, .83, 1.5, false, '1 orc steel ingot', 'dol guldur spear'),
    new Weapon(7.5, .5, 2, false, '2 orc steel ingot', 'dol guldur spike'),
    new Weapon(5, 1.5, .75, false, '1 elven steel ingot', 'dorwinion elven dagger'),
    new Weapon(8, 1, 1, false, '2 elven steel ingot', 'dorwinion elven sword'),
    new Weapon(6.5, .83, 1.5, false, '1 dwarven steel ingot', 'spear of bladorthin'),
    new Weapon(5, .65, 1, true, '3 planks', 'dunlending club'),
    new Weapon(7, .68, 1.5, false, '3 iron ingots', 'dunlending trident'),
    new Weapon(5, 1.5, .75, false, '1 dwarven steel ingot', 'dwarven dagger'),
    new Weapon(8, 1, 1, false, '2 dwarven steel ingots', 'dwarven sword'),
    new Weapon(10, .75, 1, false, '5 dwarven steel ingots', 'dwarven battleaxe'),
    new Weapon(11, .65, 1, true, '4 dwarven steel ingots', 'dwarven warhammer'),
    new Weapon(7, .83, 1.5,false, '1 dwarven steel ingot', 'dwarven spear'),
    new Weapon(8, .5, 2, false, '2 dwarven steel ingots', 'dwarven pike'),
    new Weapon(5, 1.5, .75, false, '1 elven steel ingot', 'galadhrim dagger'),
    new Weapon(8, 1.1, .75, false, '2 elven steel ingots', 'galadhrim sword'),
    new Weapon(7, .83, 1.5, false, '1 elven steel ingot', 'galadhrim spear'),
    new Weapon(8, .5, 2, false, '2 elven steel ingots', 'galadhrim longspear'),
    new Weapon(8, .68, 1.5, false, '2 elven steel ingots', 'galadhrim battlestaff'),
    new Weapon(10, 1, 1, false, 'CBC', 'gondolinian sword'),
    new Weapon(7.5, 1, 1, false, '2 iron ingots', 'gondorian sword'),
    new Weapon(4.5, 1.5, .75, false, '1 iron ingots', 'gondorian dagger'),
    new Weapon(10.5, .65, 1, true, '4 iron ingots', 'gondorian warhammer'),
    new Weapon(6.5, .83, 1.5, false, '1 iron ingot', 'gondorian spear'),
    new Weapon(7.5, .5, 2, true, '2 iron ingot', 'gondorian lance'),
    new Weapon(7.5, .5, 2, false, '2 iron ingot', 'gondorian pike'),
    new Weapon(7.5, 1, 1, false, '2  bronze ingots', 'gulfen khopesh'),
    new Weapon(4.5, 1.5, .75, false, '1 flint', 'half-troll dagger'),
    new Weapon(7.5, 1, 1, false, '2 flint', 'half-troll dagger'),
    new Weapon(7.5, .5, 2, false, '2 flint', 'half-troll pike'),
    new Weapon(10.5, .65, 1, true, '4 flint', 'half-troll warhammer'),
    new Weapon(10.5, .65, 1, true, '4 flint', 'half-troll mace'),
    new Weapon(9.5, .75, 1, false, '5 flint', 'half-troll battleaxe'),
    new Weapon(7.5, 1, 1, false, '2 bronze ingots', 'haradic sword'),
    new Weapon(4.5, 1.5, .75, false, '1 bronze ingot', 'haradic dagger'),
    new Weapon(6.5, .83, 1.5, false, '1 bronze ingot','haradic spear'),
    new Weapon(7.5, .5, 2, false, '2 bronze ingots', 'haradic longspear'),
    new Weapon(9.5, .68, 1, true, 'CBC', 'blacksmith hammer'),
    new Weapon(5, 1.5, .75, false, '1 elven steel ingot', 'lindon dagger'),
    new Weapon(8, 1, 1, false, '2 elven steel ingots', 'lindon sword'),
    new Weapon(7, .83, 1.5,  false, '1 elven steel ingot', 'lindon spear'),
    new Weapon(8, .65, 1.5, false, '2 elven steel ingots', 'lindon battlestaff'),
    new Weapon(8, .5, 2, false, '2 elven steel ingots', 'lindon longspear'),
    new Weapon(9, .75, 1, false, '5 iron ingots', 'lossarnach battleaxe'),
    new Weapon(6.5, 1, 1, false, '2 mallorn planks', 'mallorn sword'),
    new Weapon(7, 1.5, .75, false, '1 mithril ingot', 'mithril dagger'),
    new Weapon(10, 1, 1, false,  '2 mithril ingots', 'mithril sword'),
    new Weapon(12, .75, 1, false, '5 mithril ingots',  'mithril battleaxe'),
    new Weapon(13, .65, 1, true, '4 mithril ingots', 'mithril warhammer'),
    new Weapon(9, .83, 1.5, false, '1 mithril ingot', 'mithril spear'),
    new Weapon(10, .5, 2, false, '3 mithril ingots','mithril halberd'),
    new Weapon(4.5, 1.5, .75, false, '1 orc steel ingot', 'mordor dagger'),
    new Weapon(7.5, 1, 1, false, '2 orc steel ingots', 'mordor scimitar'),
    new Weapon(6.5, .83, 1.5, false, '1 orc steel ingot', 'mordor spear'),
    new Weapon(8.5, .75, 1, false, '5 orc steel ingots', 'mordor battleaxe'),
    new Weapon(9.5, .65, 1, true, '4 orc steel ingots', 'mordor warhammer'),
    new Weapon(7.5, .68, 1.5, false, '3 orc steel ingots', 'mordor warscythe'),
    new Weapon(4.5, 1.5, .75, false, 'CBC', 'old-haradic sacrificial dagger'),
    new Weapon(6.5, 1, 1, true, '1 skeleton skull', 'orc skull staff'),
    new Weapon(7.5, .68, 1.5, false, '3 iron ingots', 'pelargir trident'),
    new Weapon(6.5, 1, 1, false, '2 iron ingots', 'pelargir eket'),
    new Weapon(5.5, 1.5, .75, false, 'CBC', 'utumno dagger'),
    new Weapon(8.5, 1, 1, false, 'CBC', 'utumno sword'),
    new Weapon(7.5, .83, 1.5, false, 'CBC', 'utumno spear'),
    new Weapon(10.5, .75, 1, false, 'CBC', 'utumno battleaxe'),
    new Weapon(11.5, .68, 1, true, 'CBC', 'utumno warhammer'),
    new Weapon(4.5, 1.5, .75, false, '1 iron ingot', 'rhûnic dagger'),
    new Weapon(7.5, 1, 1, false, '2 iron ingot', 'rhûnic sword'),
    new Weapon(6.5, .83, 1.5, false, '1 iron ingot', 'rhûnic spear'),
    new Weapon(7.5, .83, 1.5, false, '3 iron ingots', 'rhûnic bardiche'),
    new Weapon(7.5, .5, 2, false, '2 iron ingots', 'rhûnic pike'),
    new Weapon(9.5, .75, 1, false, '5 iron ingots', 'rhûnic battleaxe'),
    new Weapon(5, 1.5, .75, false, '1 elven steel ingot', 'rivendell dagger'),
    new Weapon(8, 1, 1, false, '2 elven steel ingots', 'rivendell sword'),
    new Weapon(7, .83, 1.5,  false, '1 elven steel ingot', 'rivendell spear'),
    new Weapon(8, .65, 1.5, false, '2 elven steel ingots', 'rivendell battlestaff'),
    new Weapon(8, .5, 2, false, '2 elven steel ingots', 'rivendell longspear'),
    new Weapon(4.5, 1.5, .75, false, '1 iron ingot', 'rohirric dagger'),
    new Weapon(7.5, 1, 1, false, '2 iron ingots', 'rohirric sword'),
    new Weapon(6.5, .83, 1.5, false, '1 iron ingot', 'rohirric spear'),
    new Weapon(9.5, .75, 1, false, '5 iron ingots', 'rohirric battleaxe'),
    new Weapon(7.5, .5, 2, false, '2 iron  ingots', 'rohirric lance'),
    new Weapon(5, 1, 1, false, '1 plank', 'rolling pin'),
    new Weapon(4.5, 1.5, .75, false,'1 iron ingot', 'umbaric dagger'),
    new Weapon(7.5,1,1, false, '2 iron ingots', 'umbaric scimitar'),
    new Weapon(6.5, .83, 1.5, false, '1 iron ingot', 'umbaric spear'),
    new Weapon(7.5, .68, 1.5, false, '3 iron ingots', 'umbaric poleaxe'),
    new Weapon(10.5, .65, 1, true, '4 iron ingots', 'umbaric mace'),
    new Weapon(7.5, .5, 2, false, '2 iron ingots', 'umbaric pike'),
    new Weapon(5, 1.5, .75, false, '1 elven steel ingot', 'wood-elven dagger'),
    new Weapon(8, 1, 1, false, '2 elven steel ingots', 'wood-elven sword'),
    new Weapon(7, .83, 1.5, false, '1 elven steel ingot', 'wood-elven spear'),
    new Weapon(8, .68, 1.5, false, '2 elven steel ingots', 'wood-elven battlestaff'),
    new Weapon(8, .5, 2, false, '2 elven ingots', 'wood-elven longspear'),    
]

source.forEach((x) => weapons[x.id] = x);
